# Generated by Django 5.1.6 on 2025-03-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.ImageField(upload_to='images')),
                ('des', models.TextField()),
                ('short_des', models.TextField()),
                ('price', models.FloatField()),
                ('sku', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('configurable', 'Configurable'), ('group', 'Groupd'), ('virtual', 'Virtual'), ('bundle', 'Bundle'), ('downloadable', 'Downloadable')], max_length=100)),
                ('sell_price', models.FloatField()),
                ('qty', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], max_length=100)),
            ],
        ),
    ]
