# Generated by Django 5.1.6 on 2025-03-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Manage Products'},
        ),
        migrations.AlterModelTable(
            name='products',
            table='coreapp_products',
        ),
    ]
