--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: holiday_papulardestinations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday_papulardestinations (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    img character varying(100) NOT NULL,
    num_of_places integer NOT NULL,
    created_at date NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_popular boolean NOT NULL
);


ALTER TABLE public.holiday_papulardestinations OWNER TO postgres;

--
-- Name: holiday_papulardestinations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holiday_papulardestinations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_papulardestinations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holiday_places; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday_places (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    img character varying(100) NOT NULL,
    "desc" text NOT NULL,
    price integer NOT NULL,
    days integer NOT NULL,
    review boolean NOT NULL,
    car character varying(100) NOT NULL
);


ALTER TABLE public.holiday_places OWNER TO postgres;

--
-- Name: holiday_places_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holiday_places ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_places_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holiday_subscribers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday_subscribers (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    is_subscribe boolean NOT NULL
);


ALTER TABLE public.holiday_subscribers OWNER TO postgres;

--
-- Name: holiday_subscribers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holiday_subscribers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_subscribers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holiday_testimonials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday_testimonials (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    des text NOT NULL,
    img character varying(100) NOT NULL,
    is_home boolean NOT NULL
);


ALTER TABLE public.holiday_testimonials OWNER TO postgres;

--
-- Name: holiday_testimonials_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holiday_testimonials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_testimonials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holiday_trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday_trips (
    id bigint NOT NULL,
    title character varying(300) NOT NULL,
    img character varying(100) NOT NULL,
    trip_date date NOT NULL,
    is_home boolean NOT NULL
);


ALTER TABLE public.holiday_trips OWNER TO postgres;

--
-- Name: holiday_trips_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holiday_trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add places	1	add_places
2	Can change places	1	change_places
3	Can delete places	1	delete_places
4	Can view places	1	view_places
5	Can add log entry	2	add_logentry
6	Can change log entry	2	change_logentry
7	Can delete log entry	2	delete_logentry
8	Can view log entry	2	view_logentry
9	Can add permission	3	add_permission
10	Can change permission	3	change_permission
11	Can delete permission	3	delete_permission
12	Can view permission	3	view_permission
13	Can add group	4	add_group
14	Can change group	4	change_group
15	Can delete group	4	delete_group
16	Can view group	4	view_group
17	Can add user	5	add_user
18	Can change user	5	change_user
19	Can delete user	5	delete_user
20	Can view user	5	view_user
21	Can add content type	6	add_contenttype
22	Can change content type	6	change_contenttype
23	Can delete content type	6	delete_contenttype
24	Can view content type	6	view_contenttype
25	Can add session	7	add_session
26	Can change session	7	change_session
27	Can delete session	7	delete_session
28	Can view session	7	view_session
29	Can add papular destinations	8	add_papulardestinations
30	Can change papular destinations	8	change_papulardestinations
31	Can delete papular destinations	8	delete_papulardestinations
32	Can view papular destinations	8	view_papulardestinations
33	Can add testimonials	9	add_testimonials
34	Can change testimonials	9	change_testimonials
35	Can delete testimonials	9	delete_testimonials
36	Can view testimonials	9	view_testimonials
37	Can add trips	10	add_trips
38	Can change trips	10	change_trips
39	Can delete trips	10	delete_trips
40	Can view trips	10	view_trips
41	Can add subscribers	11	add_subscribers
42	Can change subscribers	11	change_subscribers
43	Can delete subscribers	11	delete_subscribers
44	Can view subscribers	11	view_subscribers
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
3	pbkdf2_sha256$870000$8vdqVd0aN6n7wYeLxjmX7e$bGT9HKJmguChbEltEtJuDRHGM7+VHP6ZEt1/qDHWxaY=	\N	f	shaloo	Shaloo	Gupta	shaloo@gmail.com	f	t	2025-02-23 14:21:18.56857+05:30
2	pbkdf2_sha256$870000$Gc5FDGLCpFd1RRV1TnaCQS$vg5KkJq8ambFqfH8ac0AdEWKRYcX/+CnWTT66nN/deE=	2025-02-24 11:20:22.641432+05:30	f	akku	Akarsh	Gupta	akku@gmail.com	f	t	2025-02-23 14:09:59.519291+05:30
1	pbkdf2_sha256$870000$IZ5L3hCFZn0y7hxUWkHsF8$TT30rUvyNo6kgJTKfQ5JVf2gA/yE1aIZUYpyrUn9SGI=	2025-02-24 12:34:37.736797+05:30	t	killer			killer@gmail.com	t	t	2025-02-23 10:46:23.303071+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-02-23 10:55:08.548619+05:30	1	Places object (1)	1	[{"added": {}}]	1	1
2	2025-02-23 11:29:30.608535+05:30	1	Places object (1)	3		1	1
3	2025-02-23 11:30:20.491808+05:30	2	Places object (2)	1	[{"added": {}}]	1	1
4	2025-02-23 11:31:42.174009+05:30	3	Places object (3)	1	[{"added": {}}]	1	1
5	2025-02-23 11:32:25.585982+05:30	4	Places object (4)	1	[{"added": {}}]	1	1
6	2025-02-23 11:33:00.275422+05:30	5	Places object (5)	1	[{"added": {}}]	1	1
7	2025-02-23 11:33:36.687136+05:30	6	Places object (6)	1	[{"added": {}}]	1	1
8	2025-02-23 11:34:10.789598+05:30	7	Places object (7)	1	[{"added": {}}]	1	1
9	2025-02-23 23:22:45.718009+05:30	1	PapularDestinations object (1)	1	[{"added": {}}]	8	1
10	2025-02-23 23:23:17.22844+05:30	2	PapularDestinations object (2)	1	[{"added": {}}]	8	1
11	2025-02-23 23:23:40.554281+05:30	3	PapularDestinations object (3)	1	[{"added": {}}]	8	1
12	2025-02-23 23:23:59.433648+05:30	4	PapularDestinations object (4)	1	[{"added": {}}]	8	1
13	2025-02-23 23:24:23.245123+05:30	5	PapularDestinations object (5)	1	[{"added": {}}]	8	1
14	2025-02-23 23:24:47.42341+05:30	6	PapularDestinations object (6)	1	[{"added": {}}]	8	1
15	2025-02-23 23:44:42.3487+05:30	1	Testimonials object (1)	1	[{"added": {}}]	9	1
16	2025-02-23 23:45:38.461339+05:30	2	Testimonials object (2)	1	[{"added": {}}]	9	1
17	2025-02-23 23:45:54.167406+05:30	3	Testimonials object (3)	1	[{"added": {}}]	9	1
18	2025-02-23 23:46:11.22645+05:30	4	Testimonials object (4)	1	[{"added": {}}]	9	1
19	2025-02-23 23:46:51.88831+05:30	1	Trips object (1)	1	[{"added": {}}]	10	1
20	2025-02-23 23:47:26.188054+05:30	2	Trips object (2)	1	[{"added": {}}]	10	1
21	2025-02-23 23:47:52.10225+05:30	3	Trips object (3)	1	[{"added": {}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	holiday	places
2	admin	logentry
3	auth	permission
4	auth	group
5	auth	user
6	contenttypes	contenttype
7	sessions	session
8	holiday	papulardestinations
9	holiday	testimonials
10	holiday	trips
11	holiday	subscribers
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-02-23 01:16:02.433714+05:30
2	auth	0001_initial	2025-02-23 01:16:02.51337+05:30
3	admin	0001_initial	2025-02-23 01:16:02.534815+05:30
4	admin	0002_logentry_remove_auto_add	2025-02-23 01:16:02.541953+05:30
5	admin	0003_logentry_add_action_flag_choices	2025-02-23 01:16:02.547647+05:30
6	contenttypes	0002_remove_content_type_name	2025-02-23 01:16:02.561532+05:30
7	auth	0002_alter_permission_name_max_length	2025-02-23 01:16:02.568394+05:30
8	auth	0003_alter_user_email_max_length	2025-02-23 01:16:02.575592+05:30
9	auth	0004_alter_user_username_opts	2025-02-23 01:16:02.581551+05:30
10	auth	0005_alter_user_last_login_null	2025-02-23 01:16:02.589192+05:30
11	auth	0006_require_contenttypes_0002	2025-02-23 01:16:02.590473+05:30
12	auth	0007_alter_validators_add_error_messages	2025-02-23 01:16:02.596114+05:30
13	auth	0008_alter_user_username_max_length	2025-02-23 01:16:02.60581+05:30
14	auth	0009_alter_user_last_name_max_length	2025-02-23 01:16:02.612201+05:30
15	auth	0010_alter_group_name_max_length	2025-02-23 01:16:02.620557+05:30
16	auth	0011_update_proxy_permissions	2025-02-23 01:16:02.626193+05:30
17	auth	0012_alter_user_first_name_max_length	2025-02-23 01:16:02.631775+05:30
18	holiday	0001_initial	2025-02-23 01:16:02.639521+05:30
19	sessions	0001_initial	2025-02-23 01:16:02.649019+05:30
20	holiday	0002_places_car	2025-02-23 01:25:04.762427+05:30
21	holiday	0003_papulardestinations	2025-02-23 16:29:58.884035+05:30
22	holiday	0004_papulardestinations_is_popular	2025-02-23 23:17:58.437138+05:30
23	holiday	0005_testimonials_trips	2025-02-23 23:40:49.41846+05:30
24	holiday	0006_subscribers	2025-02-24 11:30:03.542733+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
pcj0wub10dirll410azy5jqrzioju5ey	e30:1tm91g:2GvkSSbHgW68GEqLy3fHnEafdCBPoyj9rA5znx6_VJs	2025-03-09 15:45:56.543828+05:30
ywratektaxd3k2wqd2qapagg5jlhmpyv	.eJxVjMEOwiAQRP-FsyFssYgevfsNZJddpGogKe3J-O9tkx7qbTLvzXxVwHnKYW4yhoHVTYE6HTvC-JayAX5heVYda5nGgfSm6J02_agsn_vu_h1kbHld286jlZ6cQ-eFwYKQmJTiGRxaYh-vnsEk64BMBEQgWbMI9xcvplO_Bfc1OHc:1tm9jn:Oz0bVqppIGuhGvIXFODkDzT3VdFaKLyaH8la06bqP-Y	2025-03-09 16:31:31.299367+05:30
583ko80upi0n0olz804uz94bbxcjlyip	.eJxVjMEOwiAQRP-FsyFssYgevfsNZJddpGogKe3J-O9tkx7qbTLvzXxVwHnKYW4yhoHVTYE6HTvC-JayAX5heVYda5nGgfSm6J02_agsn_vu_h1kbHld286jlZ6cQ-eFwYKQmJTiGRxaYh-vnsEk64BMBEQgWbMI9xcvplO_Bfc1OHc:1tmSW5:-z3Pf8N4QdSNSLVAUfa8WytBZdrK0tvQv414MmLt5gg	2025-03-10 12:34:37.739358+05:30
\.


--
-- Data for Name: holiday_papulardestinations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.holiday_papulardestinations (id, name, img, num_of_places, created_at, updated_at, is_popular) FROM stdin;
1	Italy	destimages/1.png	7	2025-02-23	2025-02-23 23:22:40+05:30	t
2	Brazil	destimages/2.png	10	2025-02-23	2025-02-23 23:23:07+05:30	t
3	America	destimages/3.png	15	2025-02-23	2025-02-23 23:23:38+05:30	t
4	Nepal	destimages/4.png	14	2025-02-23	2025-02-23 23:23:58+05:30	t
5	Maldivas	destimages/5.png	16	2025-02-23	2025-02-23 23:24:22+05:30	t
6	Indonesia	destimages/6.png	19	2025-02-23	2025-02-23 23:24:44+05:30	t
\.


--
-- Data for Name: holiday_places; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.holiday_places (id, name, img, "desc", price, days, review, car) FROM stdin;
2	Mumbai	places/mumbai.jpeg	The City That Never Sleeps	600	4	t	BMW
3	Hyderabad	places/hydrabad.jpeg	First Biryani Then Sherwani	450	4	f	swift
4	Delhi	places/delhi.jpeg	The People Of Heart	350	3	t	Breeza
5	Kolkata	places/kolkata.jpeg	The City Of Magic	800	6	t	Swift
6	Varansi	places/varansi.jpeg	The City Of Mahadev	1000	9	t	BMW
7	Nainital	places/nainital.jpeg	The City Of Heels	1200	12	t	swift
\.


--
-- Data for Name: holiday_subscribers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.holiday_subscribers (id, email, is_subscribe) FROM stdin;
1	Akasrh089@gmail.com	t
2	abc@gmail.com	t
\.


--
-- Data for Name: holiday_testimonials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.holiday_testimonials (id, name, des, img, is_home) FROM stdin;
1	Jery mause	Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering	testimonials/author.png	t
2	Lina	Lorem Ipsum is simply dummy text of the printing and typesetting industry	testimonials/2.jpeg	t
3	Malaika	Lorem Ipsum is simply dummy text of the printing and typesetting industry	testimonials/3.jpeg	t
4	Shaloo Gupta	Lorem Ipsum is simply dummy text of the printing and typesetting industry	testimonials/4.jpeg	t
\.


--
-- Data for Name: holiday_trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.holiday_trips (id, title, img, trip_date, is_home) FROM stdin;
1	Journeys Are Best Measured In New Friends	trips/1.png	2024-08-13	t
2	Lorem Ipsum is simply dummy text of	trips/2.png	2024-08-16	t
3	Lorem Ipsum is simply dummy text of the	trips/3.png	2024-01-18	t
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 21, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: holiday_papulardestinations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.holiday_papulardestinations_id_seq', 6, true);


--
-- Name: holiday_places_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.holiday_places_id_seq', 7, true);


--
-- Name: holiday_subscribers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.holiday_subscribers_id_seq', 2, true);


--
-- Name: holiday_testimonials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.holiday_testimonials_id_seq', 4, true);


--
-- Name: holiday_trips_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.holiday_trips_id_seq', 3, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: holiday_papulardestinations holiday_papulardestinations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.holiday_papulardestinations
    ADD CONSTRAINT holiday_papulardestinations_pkey PRIMARY KEY (id);


--
-- Name: holiday_places holiday_places_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.holiday_places
    ADD CONSTRAINT holiday_places_pkey PRIMARY KEY (id);


--
-- Name: holiday_subscribers holiday_subscribers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.holiday_subscribers
    ADD CONSTRAINT holiday_subscribers_pkey PRIMARY KEY (id);


--
-- Name: holiday_testimonials holiday_testimonials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.holiday_testimonials
    ADD CONSTRAINT holiday_testimonials_pkey PRIMARY KEY (id);


--
-- Name: holiday_trips holiday_trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.holiday_trips
    ADD CONSTRAINT holiday_trips_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

