# Generated by Django 5.1.6 on 2025-03-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=100)),
            ],
            options={
                'verbose_name': 'Manage Course',
                'db_table': 'course_course',
            },
        ),
    ]
