# Generated by Django 5.1.6 on 2025-04-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
