# Generated by Django 5.1.6 on 2025-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
