# Generated by Django 5.1.7 on 2025-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_products_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author2',
        ),
    ]
