# Generated by Django 5.1.7 on 2025-04-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author3',
        ),
    ]
