# Generated by Django 5.1.7 on 2025-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Manage Books', 'verbose_name_plural': 'Manage Books 2'},
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
    ]
