# Generated by Django 5.1.7 on 2025-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_author_options_customer_age_gte_18'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCollege',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='age_gte_18',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 18)), name='age'),
        ),
    ]
