# Generated by Django 5.1.6 on 2025-03-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('courses', models.CharField(choices=[('bca', 'BCA'), ('mca', 'MCA'), ('mba', 'MBA')], max_length=50)),
                ('video_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Manage Courses',
                'db_table': 'courses_courses',
            },
        ),
    ]
