# Generated by Django 5.1.6 on 2025-02-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='places')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('review', models.BooleanField(default=False)),
            ],
        ),
    ]
