# Generated by Django 5.1.6 on 2025-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_places_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapularDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='destimages')),
                ('num_of_places', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
