# Generated by Django 5.1.6 on 2025-02-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_papulardestinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='papulardestinations',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
