# Generated by Django 5.1.6 on 2025-02-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0005_testimonials_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_subscribe', models.BooleanField()),
            ],
        ),
    ]
