# Generated by Django 5.1.6 on 2025-02-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0006_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='desc',
            new_name='description',
        ),
    ]
